# Test Benchmark

## Buffer

buffer store function (multi done scenario)

In [1]:
from agent import AgentSAC
from attrdict import AttrDict
import torch
import yaml
from envs import toy

with open(f'configs/debug.yaml', "r") as stream:
  try:
    cfg = AttrDict(yaml.safe_load(stream))
  except yaml.YAMLError as exc:
    print(exc)
agent = AgentSAC(cfg)

/home/reed/miniconda3/envs/rlgpu/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/reed/miniconda3/envs/rlgpu/lib/python3.7/site-packages/gym/spaces/box.py:84: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")


In [2]:
traj = agent.explore_vec_env()

In [3]:
agent.buffer.data[:12]

tensor([[ 5.7474e-01, -7.3119e-01, -9.6110e-01,  5.4669e-01, -1.0000e+00,
          9.9000e-01, -3.5703e-01,  6.3359e-01,  0.0000e+00,  1.0000e+00,
          0.0000e+00,  0.0000e+00,  1.4013e-45,  5.0333e-01, -6.0447e-01],
        [ 5.0333e-01, -6.0447e-01, -9.6110e-01,  5.4669e-01, -1.0000e+00,
          9.9000e-01,  2.2899e-01,  5.6891e-01,  0.0000e+00,  2.0000e+00,
          0.0000e+00,  0.0000e+00,  1.4013e-45,  5.4913e-01, -4.9069e-01],
        [ 5.4913e-01, -4.9069e-01, -9.6110e-01,  5.4669e-01, -1.0000e+00,
          9.9000e-01, -6.7779e-01,  9.4470e-01,  0.0000e+00,  3.0000e+00,
          0.0000e+00,  0.0000e+00,  1.4013e-45,  4.1357e-01, -3.0175e-01],
        [ 4.1357e-01, -3.0175e-01, -9.6110e-01,  5.4669e-01, -1.0000e+00,
          9.9000e-01,  2.5347e-01,  5.8554e-01,  0.0000e+00,  4.0000e+00,
          0.0000e+00,  0.0000e+00,  1.4013e-45,  4.6426e-01, -1.8464e-01],
        [ 4.6426e-01, -1.8464e-01, -9.6110e-01,  5.4669e-01, -1.0000e+00,
          9.9000e-01, -8.5612e-01,

In [4]:
trans = agent.buffer.sample_batch(10, her_rate=1, indices=torch.arange(20, device='cuda:0'))

In [5]:
obs_dict = agent.EP.obs_parser(trans.state[:20])
obs_dict.ag, obs_dict.g

(tensor([[ 0.5747, -0.7312],
         [ 0.5033, -0.6045],
         [ 0.5491, -0.4907],
         [ 0.4136, -0.3017],
         [ 0.4643, -0.1846],
         [ 0.2930, -0.1274],
         [ 0.4421, -0.2117],
         [ 0.3383, -0.1028],
         [ 0.3868, -0.2946],
         [ 0.5395, -0.4388],
         [ 0.4048, -0.5784],
         [ 0.5151, -0.5928],
         [ 0.3989, -0.4425],
         [ 0.5107, -0.2869],
         [ 0.6485, -0.1337],
         [ 0.6347, -0.1763],
         [ 0.7884,  0.0058],
         [ 0.6210,  0.0436],
         [ 0.7628,  0.1938]], device='cuda:0'),
 tensor([[ 0.5033, -0.6045],
         [ 0.5491, -0.4907],
         [ 0.4136, -0.3017],
         [ 0.4643, -0.1846],
         [ 0.2930, -0.1274],
         [ 0.4421, -0.2117],
         [ 0.3383, -0.1028],
         [ 0.3868, -0.2946],
         [ 0.5395, -0.4388],
         [ 0.4048, -0.5784],
         [ 0.5151, -0.5928],
         [ 0.3989, -0.4425],
         [ 0.5107, -0.2869],
         [ 0.6485, -0.1337],
         [ 0.6347, -0.17

HER buffer

In [ ]:
buffer.buf_other[:20][..., :2]

# Wandb

In [ ]:
import wandb
wandb.init(project="debug")