# Test Benchmark

## Buffer

buffer store function (multi done scenario)

In [1]:
from agent import AgentSAC
from attrdict import AttrDict
import torch
import yaml
from envs import toy

with open(f'configs/debug.yaml', "r") as stream:
  try:
    cfg = AttrDict(yaml.safe_load(stream))
  except yaml.YAMLError as exc:
    print(exc)
agent = AgentSAC(cfg)

/home/reed/miniconda3/envs/rlgpu/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/reed/miniconda3/envs/rlgpu/lib/python3.7/site-packages/gym/spaces/box.py:84: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")


In [2]:
traj = agent.explore_vec_env()

In [ ]:
agent.buffer.data_parser(agent.buffer.data[:10], 'info.tleft')

In [3]:
trans = agent.buffer.sample_batch(10, her_rate=0.5, indices=torch.arange(10, device='cuda:0'))

In [5]:
obs_dict = agent.EP.obs_parser(trans.state[:10])
obs_dict.ag, obs_dict.g, trans.rew

(tensor([[ 0.5747, -0.7312],
         [ 0.5033, -0.6045],
         [ 0.5491, -0.4907],
         [ 0.4136, -0.3017],
         [ 0.4643, -0.1846],
         [ 0.2930, -0.1274],
         [ 0.4421, -0.2117],
         [ 0.3383, -0.1028],
         [ 0.3868, -0.2946]], device='cuda:0'),
 tensor([[ 0.3383, -0.1028],
         [ 0.2930, -0.1274],
         [ 0.4136, -0.3017],
         [ 0.4643, -0.1846],
         [ 0.5395, -0.4388],
         [-0.9611,  0.5467],
         [-0.9611,  0.5467],
         [-0.9611,  0.5467],
         [-0.9611,  0.5467]], device='cuda:0'),
 tensor([-1., -1., -0., -0., -1., -1., -1., -1., -1.], device='cuda:0'))

In [ ]:
info_dict = agent.EP.info_parser(trans.info[:20])
info_dict.step

HER buffer

In [ ]:
buffer.buf_other[:20][..., :2]

# Wandb

In [ ]:
import wandb
wandb.init(project="debug")